routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() {
    return redirect('/register');
});
Route::get('/register', 'Auth\RegisterController@main')->name('register');
Route::post('/register', 'Auth\HandleRegisterController@main')->name('register');
Route::get('/login', 'Auth\LoginController@main')->name('login');
Route::post('/login', 'Auth\HandleLoginController@main')->name('login');
Route::get('/password/forgot', 'Auth\ForgotPasswordController@main')->name('password.forgot');
Route::post('/password/forgot', 'Auth\ChangePasswordController@main')->name('password.forgot');


Route::group([
    'namespace' => 'Admin',
    'middleware' => 'auth',
    'prefix' => 'admin',
], function () {
    Route::get('/logout', 'LogoutController@main')->name('logout');
    Route::get('/dashboard', 'DashboardController@main')->name('dashboard');
    Route::get('/profile', 'ProfileController@main')->name('profile');
    Route::post('/profile', 'UpdateProfileController@main')->name('profile.update');
    Route::get('/', 'DashboardController@main')->name('home');
    Route::group([
        'namespace' => 'User',
        'prefix' => 'user',
    ], function () {
        Route::get('/list', 'ListController@main')->name('user.list');
        Route::get('/create', 'CreateController@main')->name('user.create')->middleware('role.admin');
        Route::post('/create', 'StoreController@main')->name('user.store')->middleware('role.admin');
        Route::get('/detail/{id}', 'DetailController@main')->name('user.detail');
        Route::post('/update/{id}', 'UpdateController@main')->name('user.update')->middleware('role.admin');
        Route::post('/delete/{id}', 'DeleteController@main')->name('user.delete')->middleware('role.admin');
    });
    Route::group([
        'namespace' => 'Account',
        'prefix' => 'account',
    ], function () {
        Route::get('/live', 'LiveListController@main')->name('account.live');
        Route::post('/delete/{login}', 'DeleteLiveAccountController@main')->name('account.live.delete')->middleware('role.admin');
        Route::get('/create/{id}', 'CreateLiveAccountController@main')->name('account.live.create')->middleware('role.admin');
        Route::post('/create', 'OpenLiveAccountController@main')->name('account.live.open')->middleware('role.admin');
        Route::get('/detail/{id}', 'DetailLiveAccountController@main')->name('account.live.detail');
        Route::post('/detail/{id}', 'UpdateLiveAccountController@main')->name('account.live.update')->middleware('role.admin');
    });
    Route::group([
        'namespace' => 'Deposit',
        'prefix' => 'deposit',
        'middleware' => 'role.admin'
    ], function () {
        Route::get('/list', 'ListController@main')->name('deposit.list');
        Route::post('/approve/{id}', 'ApproveController@main')->name('deposit.approve');
    });
    Route::group([
        'namespace' => 'Withdrawal',
        'prefix' => 'withdrawal',
        'middleware' => 'role.admin'
    ], function () {
        Route::get('/list', 'ListController@main')->name('withdrawal.list');
        Route::post('/approve/{id}', 'ApproveController@main')->name('withdrawal.approve');
    });
    Route::group([
        'namespace' => 'Agent',
        'prefix' => 'agent',
    ], function () {
        Route::get('/customer/link', 'LinkController@main')->name('customer.link');
        Route::get('/link', 'AgentLinkController@main')->name('agent.link');
        Route::get('/list', 'ListController@main')->name('agent.list');
        Route::get('/detail/{id}', 'DetailController@main')->name('agent.detail');
        Route::post('/detail/{id}', 'UpdateController@main')->name('agent.update');
        Route::post('/active/{id}', 'ActiveController@main')->name('agent.active');
        Route::get('/link-managet-agent/{id}', 'ListController@listStaffManager')->name('agent.manager-staff');
        Route::get('/list-status-noactive/{id}', 'ListController@listStaffNoActive')->name('agent.list-status-noactive');
    });
    Route::group([
        'namespace' => 'Report',
        'prefix' => 'report',
    ], function () {
        Route::get('/trade', 'GetTradeListController@main')->name('report.trade');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model
{

    use SoftDeletes;

    protected $fillable = [
        'email',
        'first_name',
        'last_name',
        'password',
        'phone_number',
        'application_type',
        'country',
        'state',
        'address',
        'zip_code',
        'city',
        'copy_of_id',
        'proof_of_address',
        'addtional_file',
        'ib_id'
    ];

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function liveAccounts()
    {
        return $this->hasMany('App\Models\LiveAccount', 'user_id');
    }

    public function orders()
    {
        return $this->hasMany('App\Models\Order');
    }
}

app/Http/Controllers/Admin/User/CreateController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CreateController extends Controller
{
    public function main()
    {
        $ibId = Auth::user()->ib_id;
        return view('admin.user.create', compact('ibId'));
    }
}

app/Http/Controllers/Admin/User/DeleteController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use App\Repositories\DepositRepository;
use App\Repositories\LiveAccountRepository;
use App\Repositories\UserRepository;
use App\Repositories\WithdrawalRepository;
use Exception;
use Illuminate\Support\Facades\DB;

class DeleteController extends Controller
{
    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * @var LiveAccountRepository
     */
    private $liveAccountRepository;
    private $withdrawalRepository;
    private $depositRepository;

    /**
     * ListController constructor.
     * @param UserRepository $userRepository
     */
    public function __construct(
        UserRepository $userRepository,
        LiveAccountRepository $liveAccountRepository,
        WithdrawalRepository $withdrawalRepository,
        DepositRepository $depositRepository
    )
    {
        $this->userRepository = $userRepository;
        $this->liveAccountRepository = $liveAccountRepository;
        $this->withdrawalRepository = $withdrawalRepository;
        $this->depositRepository = $depositRepository;
    }

    public function main($id)
    {
        try {
            DB::beginTransaction();
            $this->userRepository->delete($id);
            $message = $this->liveAccountRepository->deleteLiveAccountByUserId($id);
            if (!empty($message)) {
                return redirect()->back()->with('error', $message);
            }
            $this->withdrawalRepository->deleteWithdrawalByUserId($id);
            $this->depositRepository->deleteDepositByUserId($id);
            DB::commit();
            return redirect()->back()->with('success', 'You delete success');
        } catch (Exception $e) {
            DB::rollBack();
            return redirect()->back()->with('error', 'You delete fail');
        }
    }
}

app/Http/Controllers/Admin/User/DetailController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DetailController extends Controller
{
    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * DetailController constructor.
     * @param UserRepository $userRepository
     */
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function main($id)
    {
        $user = $this->userRepository->find($id);
        $isAdmin = Auth::user()->role == config('role.admin');
        return view('admin.user.detail', compact('user', 'isAdmin'));
    }
}

app/Http/Controllers/Admin/User/ListController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;

class ListController extends Controller
{
    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * ListController constructor.
     * @param UserRepository $userRepository
     */
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function main(Request $request)
    {
        $data = $request->except('_token');
        $userList = $this->userRepository->getUserListBySearch($data);
        return view('admin.user.list', compact('userList', 'data'));
    }
}

app/Http/Controllers/Admin/User/StoreController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use App\Mail\CreateUserSuccess;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use App\Repositories\UserRepository;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Mail;
use App\Repositories\PasswordResetRepository;
use Illuminate\Support\Carbon;

class StoreController extends Controller
{

    /**
     * @var UserRepository
     */
    private $userRepository;
    private $passwordResetRepository;

    /**
     * ListController constructor.
     * @param UserRepository $userRepository
     */
    public function __construct(UserRepository $userRepository, PasswordResetRepository $passwordResetRepository)
    {
        $this->userRepository = $userRepository;
        $this->passwordResetRepository = $passwordResetRepository;
    }

    public function main(Request $request)
    {
        $data = $request->except('_token');
        $validateData = $this->validateData($data);
        if ($validateData->fails()) {
            return redirect()->back()->withErrors($validateData->errors())->withInput();
        }
        $data['password'] = Hash::make(Str::random(8));
        $user = $this->userRepository->create($data);
        if ($user) {
            $email = $user->email;
            $token = $this->createToken($email);
            Mail::to($email)->send(new CreateUserSuccess($user, $token));
            return back()->with('success', "You are created success");
        } else {
            return back()->with('error', "You are created fail");
        }
    }

    public function validateData($data)
    {
        $countries = config('country');
        return Validator::make(
            $data,
            [
                'email'        => 'required|email|unique:users',
                'first_name'   => 'required|string|max:255',
                'last_name'    => 'required|string|max:255',
                'country'      => ['required', Rule::in(array_keys($countries))],
                'phone_number' => 'required|regex:/[0-9]{10,11}/',
                'ib_id'        => 'bail|required|regex:/[0-9]{6}/',
            ],
            [
                'ib_id.regex' => 'The IB ID has only 6 digits',
            ]
        );
    }

    private function createToken($email)
    {
        $key = config('app.key');
        if (Str::startsWith($key, 'base64:')) {
            $key = base64_decode(substr($key, 7));
        }
        $token = hash_hmac('sha256', Str::random(40), $key);
        $this->passwordResetRepository->updateOrCreate(
            ['email' => $email],
            [
                'token'      => $token,
                'email'      => $email,
                'created_at' => Carbon::now(),
            ]
        );
        return $token;
    }
}

app/Http/Controllers/Admin/User/UpdateController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use App\Repositories\UserRepository;
use Illuminate\Support\Facades\DB;

class UpdateController extends Controller
{

    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * ListController constructor.
     * @param UserRepository $userRepository
     */
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function main($id, Request $request)
    {
        $data = $request->except('_token');
        $validateData = $this->validateData($data);
        if ($validateData->fails()) {
            return redirect()->back()->withErrors($validateData->errors())->withInput();
        }
        $result = $this->userRepository->updateUser($id, $data);
        if (!is_null($result)) {
            return redirect()->back()->with('error', $result);
        }
        return redirect()->back()->with('success', 'You are updated success');
    }

    public function validateData($data)
    {
        $countries = config('country');
        return Validator::make(
            $data,
            [
                'first_name'       => 'required|string|max:255',
                'last_name'        => 'required|string|max:255',
                'country'          => ['required', Rule::in(array_keys($countries))],
                'phone_number'     => 'required|regex:/[0-9]{10,11}/',
                "city"             => 'nullable|string|max:255',
                "state"            => 'nullable|string|max:255',
                "zip_code"         => 'nullable|string|max:255',
                "address"          => 'nullable|string|max:255',
                'copy_of_id'       => 'bail|nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'addtional_file'   => 'bail|nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'proof_of_address' => 'bail|nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'ib_id'            => 'bail|required|regex:/[0-9]{6}/',
            ],
            [
                'ib_id.regex' => 'The IB ID has only 6 digits',
            ]
        );
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.base')

@section('css')
@endsection

@section('content')

<div class="container-fluid">
    @if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
    @endif
    @if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
    @endif
    <form method="post" action="{{ route('user.store') }}">
        @csrf
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>First name</label>
                <input class="form-control" type="text" name="first_name" value="{{ old('first_name') }}" required>
                @if($errors->has('first_name'))
                <span class="text-danger text-md-left">{{ $errors->first('first_name') }}</span>
                @endif
            </div>
            <div class="form-group col-md-6">
                <label>Last name</label>
                <input class="form-control" type="text" name="last_name" value="{{ old('last_name') }}" required>
                @if($errors->has('last_name'))
                <span class="text-danger text-md-left">{{ $errors->first('last_name') }}</span>
                @endif
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Email</label>
                <input class="form-control" type="email" name="email" value="{{ old('email') }}" required>
                @if($errors->has('email'))
                <span class="text-danger text-md-left">{{ $errors->first('email') }}</span>
                @endif
            </div>
            <div class="form-group col-md-3">
                <label>Phone number</label>
                <input class="form-control" type="text" name="phone_number" value="{{ old('phone_number') }}" required>
                @if($errors->has('phone_number'))
                <span class="text-danger text-md-left">{{ $errors->first('phone_number') }}</span>
                @endif
            </div>
            <div class="form-group col-md-3">
                <label>IB ID</label>
                <input class="form-control" type="text" name="ib_id" value="{{ old('ib_id', $ibId) }}" required @if(!is_null($ibId)) readonly @endif>
                @if($errors->has('ib_id'))
                    <span class="text-danger text-md-left">{{ $errors->first('ib_id') }}</span>
                @endif
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Country</label>
                <select id="country" class="form-control" name="country">
                    <option value="">Choose...</option>
                    @foreach(config('country') as $key => $country)
                        @if(old('country') == $key)
                            <option value="{{ $key }}" selected>{{ $country }}</option>
                        @else
                            <option value="{{ $key }}">{{ $country }}</option>
                        @endif
                    @endforeach
                </select>
                @if($errors->has('country'))
                <span class="text-danger text-md-left">{{ $errors->first('country') }}</span>
                @endif
            </div>
            <div class="form-group col-md-6">
                <label>Application type</label>
                <select name="application_type" id="application_type" class="form-control">
                    <option value="1">Individual</option>
                    <option value="2">Join</option>
                </select>
                @if($errors->has('application_type'))
                <span class="text-danger text-md-left">{{ $errors->first('application_type') }}</span>
                @endif
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

@endsection

resources/views/admin/user/list.blade.php
@extends('layouts.base')

@section('content')
    <div class="container-fluid">
        @if ($message = Session::get('error'))
            <div class="alert alert-danger alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
        @endif
        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
        @endif
        @if(\Illuminate\Support\Facades\Auth::user()->role == config('role.admin'))
            <a style="margin-bottom: 40px" href="{{ route('user.store') }}" class="btn btn-info">Create</a>
        @endif
        <div class="form-search row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <form method="get" action="{{ route('user.list') }}">
                    @csrf
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <input class="form-control" type="text" name="email" value="{{ $data['email'] ?? '' }}"
                                   style="height: 40px" placeholder="Email">
                        </div>
                        <div class="form-group col-md-4">
                            <input class="form-control" type="text" name="login" value="{{ $data['login'] ?? '' }}"
                                   style="height: 40px" placeholder="Login">
                        </div>
                        <div class="form-group col-md-4">
                            <input class="form-control" type="text" name="ib_id" value="{{ $data['ib_id'] ?? '' }}"
                                   style="height: 40px" placeholder="IB ID">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary" style="margin-top: 10px">Search</button>
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
        <div class="table-responsive" style="margin-top: 70px">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">IB ID</th>
                    <th scope="col">Full Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone number</th>
                    <th scope="col">Address</th>
                    <th scope="col">Country</th>
                    <th scope="col">Copy_of_id</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                @foreach($userList as $key => $user)
                    <tr>
                        <th scope="row">{{ $key + 1 }}</th>
                        <th>{{ $user->ib_id }}</th>
                        <td>{{ $user->full_name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->phone_number }}</td>
                        <td>{{ $user->address }}</td>
                        <td>{{ $user->country }}</td>
                        <td>
                            <img style="height: 75px" src="{{ $user->copy_of_id }}">
                        </td>
                        <td style="width: 14%">
                            <a href="{{ route('user.detail', $user->id) }}"
                               class="btn btn-sm btn-success bold uppercase"
                               title="Edit"><i class="fa fa-edit"></i> </a>
                            @if(\Illuminate\Support\Facades\Auth::user()->role == config('role.admin'))
                                <a style="color:white" class="btn btn-sm btn-danger bold uppercase btn-delete-user"
                               data-toggle="modal" data-target="#deleteUser" data-id="{{ $user->id }}"
                               data-name="{{ $user->full_name }}"><i class="fa fa-trash-o" aria-hidden="true"></i> </a>
                            @endif
                        </td>
                    </tr>
                    <!-- Modal -->
                @endforeach
                </tbody>
            </table>
        </div>
        {!! $userList->appends(request()->input())->links() !!}
    </div>
    <div class="modal fade" id="deleteUser" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete customer</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <form method="post" id="delete-user">
                        @csrf
                        <a href="#" class="btn btn-secondary" data-dismiss="modal">Destroy</a>
                        <a href="#" onclick="$(this).closest('form').submit();" class="btn btn-primary">Xóa</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascript')
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script>
        $('.btn-delete-user').on('click', function () {
            let currentUrl = window.location.origin
            let id = $(this).attr('data-id');
            let name = $(this).attr('data-name');
            $('.modal-body').html("Are you want to delete customer " + name +
                " and all out account ?");
            let redirectUrl = currentUrl + '/admin/user/delete/' + id;
            $("#delete-user").attr('action', redirectUrl);
        })

    </script>
@endsection